[package]
name = "vin"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vin-core = { path = "src/vin-core", version = "*" }
vin-macros = { path = "src/vin-macros", version = "*" }

[dev-dependencies]
tracing-subscriber = "0.3"

[workspace]
members = ["src/vin-macros", "src/vin-core"]