[package]
name = "vin-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
tokio = { version = "1.21", features = ["sync", "parking_lot", "time"] }
lazy_static = "1.4"